server:
 port: 8080
 error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
 #servlet:
    #context-path: /car-rental/api
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrental_db
    username: carrentaluser
    password: user
    driver-class-name: org.postgresql.Driver
  
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
      ddl-auto: update
   properties:
      format-sql: true
      #hibernate:
        #enable_lazy_load_no_trans: true
        
   # open-in-view değeri default olarak true geliyor. İlişki lazy yapılsa dahi view render edilene kadar veya json datası oluşana kadar transaction açık kalıyor.
   # open-in-view : false
      
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
        

greenrent: 
  app: 
    jwtSecret: greenRent@12
    jwtExpressionMs: 86400000

logging:
 file:
  name: logs/greenrent.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
 level:
   '[org.springframework.web]': INFO
   '[org.hibernate]': INFO
   '[com.greenrent]': DEBUG

info:
 application:
  name: 'GreenRent Backend App.'
  description: 'This is GreenRent Backend app dev by Green Rent Dev Team'
  version: '@project.version@'
